# fly.toml app configuration file generated for titan-shop-back-end on 2023-07-25T16:36:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titan-shop-back-end"
primary_region = "hkg"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  CORS_ORIGIN_OPTION="*"
  JWT_SECRET="secret"

  DB_USERNAME="admin"
  DB_PASSWORD="26604079"
  DB_DATABASE="titan_shop"
  DB_HOST="flydatabase.internal"

[deploy]
  release_command = "npx sequelize db:migrate"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
